### ISSUE TITLE
Y game no work

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [BrandonE/mmbno#1]
how come you no have play

**Comment by Keristero** [comment]
i want no 2!

**Comment by TheMaverickProgrammer** [comment]
Hey I'm hosting a stream! Chat and I would like to play your game. Is phaser the latest branch?

**Comment by BrandonE** [comment]
Hey! This was a fun little project I worked on a long time ago. Unfortunately, I haven't been able to continue it. `phaser` is the branch where I started to implement the frontend. You're welcome to continue the project! The backend code is pretty throughly implemented at this point.

**Comment by TheMaverickProgrammer** [comment]
Chat and I played. We liked what we saw! I've got a community of BN obsessives so if you ever pick it up again please reach out and I'll share it with them!

**Comment by BrandonE** [comment]
That's really cool, @TheMaverickProgrammer ! If it was clipped, I'd love to see it.
